'''
Plugsy - KeyLogger
@note - Generated by PlugSy SDK
'''

#Import libs
from plugsy.AbstractPlugin import AbstractPlugin
import time

# Import any package content

class KeyLogger(AbstractPlugin):
    '''
    KeyLogger class
    '''

    def __init__(self, plugsy):
        '''
        Constructor. Call parent init fam
        '''
        AbstractPlugin.__init__(self, plugsy)


    def run(self):
        '''
        @summary: Main run method.
        @return:
        '''
        self.logger.debug("run(): ENTRY!")
        self.logger.info("KeyLogger running!")

        while not self.stop_event.is_set():
            pass

        self.logger.info("KeyLogger stopping!")
        self.logger.debug("run(): EXIT!")


    def print_contents(self):

        return "hello"
