'''
Plugsy - PluginTemplate
@note - Generated by PlugSy SDK
'''

#Import libs
import time

# Import Package and PlugSy Modules
from plugsy.AbstractPlugin import AbstractPlugin

class PluginTemplate(AbstractPlugin):
    '''
    PluginTemplate class
    '''

    def __init__(self, plugsy):
        '''
        Constructor. Call parent init fam
        '''
        AbstractPlugin.__init__(self, plugsy)


    def run(self):
        '''
        @summary: Main run method.
        @return:
        '''
        self.logger.debug("ENTRY!")
        self.logger.info("PluginTemplate running!")

        while not self.stop_event.is_set():
            pass

        self.logger.info("PluginTemplate stopping!")
        self.logger.debug("EXIT!")
