'''
Plugsy - PluginTemplate
@note - Generated by PlugSy SDK
'''

#Import libs
from plugsy.AbstractPlugin import AbstractPlugin
import time

# Import any package content

class PluginTemplate(AbstractPlugin):
    '''
    PluginTemplate class
    '''

    def __init__(self, plugsy):
        '''
        Constructor. Call parent init fam
        '''
        AbstractPlugin.__init__(self, plugsy)


    def run(self):
        '''
        @summary: Main run method.
        @return:
        '''
        print("PluginTemplate running!")

        while not self.stop_event.is_set():
            pass

        print("PluginTemplate: Stopping!")
